# Generated by Django 2.2.9 on 2020-06-04 15:22

from django.db import migrations, models
import macaddress.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Address',
            fields=[
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=32)),
                ('eth0', macaddress.fields.MACAddressField(blank=True, integer=True, null=True)),
                ('host', models.CharField(max_length=200, unique=True)),
                ('sap_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
