# Generated by Django 2.2.9 on 2020-06-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_address',
            name='name',
        ),
    ]
