# Generated by Django 2.2.9 on 2020-06-05 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_api', '0003_auto_20200605_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_address',
            name='id',
        ),
        migrations.AlterField(
            model_name='ip_address',
            name='sap_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
