# Generated by Django 2.2.9 on 2020-06-05 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_api', '0004_auto_20200605_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_address',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ip_address',
            name='sap_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
